### ISSUE TITLE
Coinmarketcap: If multiple quotes are provided only the last one is returned.

### ISSUE THREAD

**Issue by Zapata** [xeroc/bitshares-pricefeed#46]
Only the last quote for each base is computed in Coinmarketcap source.

For example with this configuration:
```
    coinmarketcap:
        klass: Coinmarketcap
        enable: True
        quotes:
            - BTC
            - BTS
        bases:
            - BTC
            - USD
```

Only 'BTC:USD' and 'BTS:USD' are computed, 'BTS:BTC' is missing.
