### ISSUE TITLE
Pass in API key for CurrencyLayer

### ISSUE THREAD

**Issue by wmbutler** [xeroc/bitshares-pricefeed#9]
https://currencylayer.com/

**Comment by xeroc** [comment]
Currencylayer is available with

```
exchanges:
    currencylayer:
        klass: CurrencyLayer
        enable: True
        api_key: 
        free_subscription: True
        quotes:
        base:
```

The services has a free subscription or uses an api key
